### ISSUE TITLE
Replace tabs by white spaces.

### ISSUE THREAD

**Issue by Lomadriel** [Mirai-Team/mirai-project#35]
I suggest to replace tab by 4 white spaces.
Indeed, Github tabs are equivalent to 8 spaces.
By example in this file, doxygen doc is offset from the code.

**Comment by CBenoit** [comment]
Agreed. I wanted to do it as well. However, about the label, I think that using the "Code Style" one is relevant.

Moreover, I suggest to wait that all branchs are merged before doing it, to avoid the risk of letting some tabs in the code.. maybe delete the current CodeLayout branch you created. Not very important since there are softwares to replace tab by spaces in no time.

**Comment by Lomadriel** [comment]
In my opinion I think that Code Layout & Formatting is more relevant. But it's the same at the end.

**Comment by Lomadriel** [comment]
Merge master into CodeLayout.

**Comment by CBenoit** [comment]
This is maybe a problem about words' sense, but "layout" and "formatting" has nothing to do with the use of tab instead of spaces. And I don't know at all in which case it could describe something about the code (except maybe if we had to chose a file format for sources files) : 
http://www.wordreference.com/enfr/layout
https://fr.wikipedia.org/wiki/Format
"Code Style" could means in this case that we choose to use space instead of tab for intendation, and all the code should adopt this "style" along with our coding "style". We also get a better "style" while looking at the code on github.
If you still think it is relevant to keep "Code Layout & Formatting", ok, but please, think about it one more time.

By the way, this issue can be closed, I merged your branch into master.
